# Generated by Django 3.1.1 on 2020-09-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('dist', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
